name: flutter_demo
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/flutter_demo/assets/images/background.png
    - packages/flutter_demo/assets/images/eggplant.png
    - packages/flutter_demo/assets/images/rectangle2.png
    - packages/flutter_demo/assets/images/fishfood.png
    - packages/flutter_demo/assets/images/watermelon.png
    - packages/flutter_demo/assets/images/vector.svg
    - packages/flutter_demo/assets/images/rectangle1.png
    - packages/flutter_demo/assets/images/line2.svg
    - packages/flutter_demo/assets/images/line1.svg
    - packages/flutter_demo/assets/images/rectangle3.png
    - packages/flutter_demo/assets/images/group.svg
    - packages/flutter_demo/assets/images/cart.svg
    - packages/flutter_demo/assets/images/home.svg
    - packages/flutter_demo/assets/images/rectangle22.png
    - packages/flutter_demo/assets/images/rectangle23.png
    - packages/flutter_demo/assets/images/menuburger.svg
